@baseurl = http://localhost:8080

POST {{baseurl}}/produtos/ HTTP/1.1
Content-Type: application/json

{
  "categoria_id": 1,
  "marca_id": 2,
  "nome": "Produto REST Client",
  "descricao": "Testando via REST Client",
  "preco": "89.90",
  "desconto": "5.00",
  "estoque": 100,
  "image_url": "https://exemplo.com/imagem.jpg"
}

###
GET {{baseurl}}/produtos

###
GET {{baseurl}}/marcas

###
GET {{baseurl}}/categorias/